from __future__ import annotations

from typing import Any

from sqlalchemy import text
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncSession

from app.schemas.historical_event import HistoricalEventRead
from app.services.historical_event_service import get_historical_event
from app.services.rule_base_service import load_rule_base_summary


async def _one(db: AsyncSession, sql: str, params: dict[str, Any]) -> dict[str, Any]:
    try:
        row = (await db.execute(text(sql), params)).mappings().first()
        return dict(row) if row else {}
    except SQLAlchemyError as exc:
        return {"error": str(exc.__class__.__name__)}


async def _many(db: AsyncSession, sql: str, params: dict[str, Any]) -> list[dict[str, Any]]:
    try:
        return [dict(row) for row in (await db.execute(text(sql), params)).mappings().all()]
    except SQLAlchemyError:
        return []


async def build_disaster_review(db: AsyncSession, event_id: str) -> dict[str, Any]:
    historical = await get_historical_event(db, event_id)
    event = HistoricalEventRead.model_validate(historical).model_dump(mode="json")
    local_event_id = (historical.data_availability or {}).get("local_event_id") or historical.event_id

    hotspot_stats = await _one(
        db,
        """
        SELECT COUNT(*) AS hotspot_count,
               MIN(observed_at) AS first_observed_at,
               MAX(observed_at) AS last_observed_at,
               MAX(frp_mw) AS max_frp_mw,
               AVG(confidence_score) AS mean_confidence
        FROM fire_hotspots
        WHERE event_id = :event_id
        """,
        {"event_id": local_event_id},
    )
    weather_stats = await _one(
        db,
        """
        SELECT COUNT(*) AS record_count,
               MIN(observed_at) AS first_observed_at,
               MAX(observed_at) AS last_observed_at,
               AVG(temperature_c) AS avg_temperature_c,
               AVG(relative_humidity_percent) AS avg_humidity_percent,
               AVG(wind_speed_m_s) AS avg_wind_speed_m_s,
               MAX(wind_speed_m_s) AS max_wind_speed_m_s,
               SUM(COALESCE(precipitation_mm, 0)) AS total_precipitation_mm
        FROM weather_hourly_observations
        WHERE event_id = :event_id
        """,
        {"event_id": local_event_id},
    )
    burned_area = await _one(
        db,
        """
        SELECT source_dataset, source_name, assessment_date, area_acres, area_m2, source_file
        FROM burned_areas
        WHERE event_id = :event_id
        ORDER BY id
        LIMIT 1
        """,
        {"event_id": local_event_id},
    )
    wind_samples = await _many(
        db,
        """
        SELECT observed_at, longitude, latitude, wind_speed_m_s, wind_direction_deg,
               wind_u_m_s, wind_v_m_s, precipitation_mm
        FROM weather_hourly_observations
        WHERE event_id = :event_id
        ORDER BY observed_at
        LIMIT 24
        """,
        {"event_id": local_event_id},
    )

    data_flags = historical.data_availability or {}
    thematic_maps = {
        "pre_fire": [
            {"id": "land_cover", "title": "Land-cover map", "source_mode": "real_data" if data_flags.get("dem") else "not_available", "source": "ESA WorldCover local raster"},
            {"id": "fuel_risk", "title": "Fuel risk map", "source_mode": "model_derived" if data_flags.get("fuel") else "not_available", "source": "WorldCover-to-fuel mapping"},
            {"id": "slope_risk", "title": "Slope risk map", "source_mode": "model_derived" if data_flags.get("dem") else "not_available", "source": "Copernicus DEM derived slope"},
            {"id": "historical_weather", "title": "Historical weather map", "source_mode": "real_data" if data_flags.get("weather") else "not_available", "source": "NASA POWER hourly weather"},
        ],
        "during_fire": [
            {"id": "hotspot_timeseries", "title": "FIRMS hotspot time series", "source_mode": "real_data" if data_flags.get("firms") else "not_available", "source": "FIRMS local observations"},
            {"id": "spread_evolution", "title": "Spread evolution", "source_mode": "model_result", "source": "Existing spread runs generated by workflow"},
            {"id": "risk_level", "title": "Risk level map", "source_mode": "model_result", "source": "Risk and Commander agents"},
            {"id": "weather_vector_rain", "title": "Wind vector and rainfall layer", "source_mode": "real_data" if wind_samples else "not_available", "source": "NASA POWER hourly wind and precipitation"},
        ],
        "post_fire": [
            {"id": "mtbs_burned_area", "title": "MTBS burned-area perimeter", "source_mode": "real_data" if data_flags.get("burned_area") else "not_available", "source": "MTBS burned area"},
            {"id": "burned_extent", "title": "Burned extent", "source_mode": "real_data" if burned_area else "not_available", "source": burned_area.get("source_dataset", "")},
            {"id": "ndvi_change", "title": "NDVI change", "source_mode": "not_available", "source": "No registered pre/post NDVI product in local event database"},
        ],
    }

    report_sections = [
        {"title": "1. Event overview", "content": f"{historical.name} occurred in {historical.region}, {historical.country}. The database records {historical.burned_area_km2} km2 burned area and {historical.duration_days} days duration."},
        {"title": "2. Fire development process", "content": f"FIRMS local table contains {hotspot_stats.get('hotspot_count', 0)} hotspot records from {hotspot_stats.get('first_observed_at')} to {hotspot_stats.get('last_observed_at')}."},
        {"title": "3. Influence factors", "content": f"NASA POWER hourly records: {weather_stats.get('record_count', 0)}; average wind {weather_stats.get('avg_wind_speed_m_s')} m/s; maximum wind {weather_stats.get('max_wind_speed_m_s')} m/s; precipitation total {weather_stats.get('total_precipitation_mm')} mm."},
        {"title": "4. Spatial risk analysis", "content": "Risk interpretation must be generated from the latest spread, terrain, fuel and protected-target analysis outputs. This review exposes available inputs and model-result placeholders without fabricating risk polygons."},
        {"title": "5. Emergency response process", "content": "Workflow outputs from spread, route planning, resource recommendation and Commander agents are linked when generated for the active event."},
        {"title": "6. Post-disaster recovery suggestions", "content": "Use MTBS burned-area extent, slope/fuel overlays and documented damaged assets to prioritize erosion control, access restoration and vegetation recovery. NDVI change is marked unavailable until a registered product exists."},
    ]

    return {
        "schema_version": "fire.disaster-review.v0.1",
        "event": event,
        "local_event_id": local_event_id,
        "source_modes": {
            "historical_event": historical.source_mode,
            "hotspots": "real_data" if data_flags.get("firms") else "not_available",
            "weather": "real_data" if data_flags.get("weather") else "not_available",
            "terrain": "real_data" if data_flags.get("dem") else "not_available",
            "fuel": "model_derived" if data_flags.get("fuel") else "not_available",
            "spread_route_commander": "model_result_when_workflow_runs",
            "user_adjustments": "user_input_when_present",
        },
        "pre_fire": {"summary": "Pre-fire layers are assembled from registered land-cover, fuel, DEM and weather products.", "maps": thematic_maps["pre_fire"], "weather_stats": weather_stats},
        "during_fire": {"summary": "During-fire analysis uses FIRMS time series, spread runs, wind vectors and rainfall intensity.", "maps": thematic_maps["during_fire"], "hotspot_stats": hotspot_stats, "wind_rain_samples": wind_samples},
        "post_fire": {"summary": "Post-fire analysis uses MTBS burned area when available and marks missing NDVI explicitly.", "maps": thematic_maps["post_fire"], "burned_area": burned_area},
        "report": {"title": f"{historical.name} Disaster Analysis Report", "sections": report_sections},
        "rule_base": load_rule_base_summary(),
    }